### ISSUE TITLE
On macOS Sierra, the app immediately closes

### ISSUE THREAD

**Issue by Altares** [Synthesia-LLC/metadata-editor#2]
I installed Mono and tried opening a dotnet window and GTK window as a test and that works.

Synthesia Metadata Editor closes when launched even though I right-clicked it and pressed the open button (to get passed gate keeper). The icon immediately closes.

Is there a way to make it work? Thank you.

**Comment by npiegdon** [comment]
We're hoping to have a fix for this soon.  The first Synthesia 11 development preview will be going out soon (two weeks?) after which getting the metadata editor running on macOS again is the top item on the priority list.

**Comment by Altares** [comment]
Thanks but is there a way to get my finger hints edited on macOS to my iPad? I mean, is there a file I can copy to a windows PC and then use the metadata editor as a temporary solution?

**Comment by npiegdon** [comment]
Yeah, the data files between the PC and Mac versions are identical.  On each computer, hold your Shift key while launching Synthesia.  That will show the configuration window.  Click the "Open data folder" button.  If you copy the fingers.xml file in that folder from your Mac to a Windows machine, the metadata editor (on the Windows machine) will be able to extract the metadata to a .synthesia file that you'll be able to use on the iPad.

**Comment by Altares** [comment]
Thank you very much. Looking forward to the next iteration (on the Mac) ;)

**Comment by npiegdon** [comment]
This took a few months longer than expected, but we just pushed a new Xamarin.Mac front-end for the Metadata Editor.  So now the Mac finally has first-class support.

Check out the 1.2.0 release.  With any luck, it should run now.  (And it's signed with Developer ID, so hopefully you won't need to bypass Gatekeeper.)

**Comment by Altares** [comment]
Thank you very much. Much more practical!
