### ISSUE TITLE
The Mac Version Does Not Work

### ISSUE THREAD

**Issue by CoolPerson879** [Synthesia-LLC/metadata-editor#3]
I Tried Using The Mac Metadata Editor But Only Folders With No Files Came

**Comment by CoolPerson879** [comment]
@Synthes

**Comment by npiegdon** [comment]
I'm not sure I understand.  If you drag a single MIDI song file into the window and release the mouse button, is it added to the list correctly?

The app should support multiple files being dragged in at once, but it doesn't know how to handle dragged in folders.
