### ISSUE TITLE
Cursor skips to the end of the text for Fingering

### ISSUE THREAD

**Issue by besi** [Synthesia-LLC/metadata-editor#4]
I'm editing Fingering information in the "Fingers" field.

Let's assume I have "t1: 1--45".
Now I Set the cursor right after the 1 and delete the `-`. The dash is deleted but the cursor skips to the very end of the text. This makes editing an existing text impossible.

The same applies for the "Parts" field.

**Comment by npiegdon** [comment]
Hmm, using Windows 10 and the 1.2.0 release of the Metadata Editor, I wasn't able to reproduce this.  Are you using the editor in a different environment?

**Comment by besi** [comment]
Yes on a Mac

**Comment by npiegdon** [comment]
Thanks!  I was able to reproduce (and fix) this.  Please try the latest 1.3.0 release and let me know if you have any more trouble.
