### ISSUE TITLE
who can help me

### ISSUE THREAD

**Issue by ivheijst** [Synthesia-LLC/metadata-editor#5]
i have in Synthesia the proble tha i do not see the buttons on the right up. What can i do too see them?
Thank you Igno

**Comment by npiegdon** [comment]
Which buttons on the right are you talking about?  Did you mean in Synthesia itself?  Or in the metadata editor?

**Comment by ivheijst** [comment]
i mean the buttons in Synthesia itself, on the right site boven.
Thank you.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by npiegdon** [comment]
This is not the place to get support for the main app.  Please send an email to support@synthesiagame.com with your question (along with which buttons you're expecting to see on the "right side above" and on which screen).  Thanks!
